flipper:
  tg-key: ${TG_KEY}
spring:
  application:
    name: smartflip
  datasource:
    hikari:
      max-lifetime: 30000
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    user:
      name: ${SMARTFLIP_USER}
      password: ${SMARTFLIP_PASSWORD}
  task:
    scheduling:
      pool:
        size: 5
server:
  port: 80